version: "3"
services:
  web:
    container_name: gitdeck
    # 対話モード
    tty: true
    # dockerfileの場所
    build:
        context: .
        dockerfile: Dockerfile.dev
    # ホストOSとコンテナ内でソースコードを共有する
    # cachedで高速化
    volumes:
      - ./webapp:/home:cached
    # コンテナ内部の3000を外部から3000でアクセスする
    ports:
      - 3000:$PORT
    environment:
      - PORT=$PORT
      - HOST=0.0.0.0
      - NUXT_ENV_GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - NUXT_ENV_GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET

