version: "3"
services:
  vue:
    container_name: issue-front
    # 対話モード
    tty: true
    # Dockerfileの場所
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    working_dir: /home
    # ホストOSとコンテナ内でソースコードを共有する
    # cachedで高速化
    volumes:
      - ./frontend:/home:cached
    # コンテナ内部の3000を外部から3000でアクセスする
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - NUXT_ENV_ACCESS_TOKEN=${ACCESS_TOKEN}

  flask:
    container_name: issue-backend
    # 対話モード
    tty: true
    # Dockerfileの場所
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    working_dir: /home
    # ホストOSとコンテナ内でソースコードを共有する
    # cachedで高速化
    volumes:
      - ./backend:/home:cached
    # コンテナ内部の5000を外部から5000でアクセスする
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    command: flask run --host 0.0.0.0 --port 5000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: issue-db
    # Dockerfileの場所
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    # cachedで高速化
    volumes:
      - "./db/data:/var/lib/mysql:cached" # データの永続化
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-ppass"]
      timeout: 20s
      retries: 10
