version: "3"
services:
  web:
    container_name: gitdeck
    # 対話モード
    tty: true
    # dockerfileの場所
    build: .
    # ホストOSとコンテナ内でソースコードを共有する
    # cachedで高速化
    volumes:
      - ./webapp:/home:cached
    # コンテナ内部の3000を外部から3000でアクセスする
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NUXT_ENV_API_KEY=$NUXT_ENV_API_KEY
      - NUXT_ENV_AUTH_DOMAIN=$NUXT_ENV_AUTH_DOMAIN
      - NUXT_ENV_PROJECT_ID=$NUXT_ENV_PROJECT_ID
      - NUXT_ENV_APP_ID=$NUXT_ENV_APP_ID
      - NUXT_ENV_MEASUREMENT_ID=$NUXT_ENV_MEASUREMENT_ID
      - NUXT_ENV_STORAGE_BUCKET=$NUXT_ENV_STORAGE_BUCKET
      - NUXT_ENV_MESSAGING_SENDER_ID=$NUXT_ENV_MESSAGING_SENDER_ID

